seg_data('E:\study\雷达数据\mydata\train\2S1\')
seg_data('E:\study\雷达数据\mydata\train\BRDM_2\')
seg_data('E:\study\雷达数据\mydata\train\BTR_60\')
seg_data('E:\study\雷达数据\mydata\train\D7\')
seg_data('E:\study\雷达数据\mydata\train\SN_132\')
seg_data('E:\study\雷达数据\mydata\train\SN_9563\')
seg_data('E:\study\雷达数据\mydata\train\SN_C71\')
seg_data('E:\study\雷达数据\mydata\train\T62\')
seg_data('E:\study\雷达数据\mydata\train\ZIL131\')
seg_data('E:\study\雷达数据\mydata\train\ZSU_23_4\')

seg_data('E:\study\雷达数据\mydata\test\2S1\')
seg_data('E:\study\雷达数据\mydata\test\BRDM_2\')
seg_data('E:\study\雷达数据\mydata\test\BTR_60\')
seg_data('E:\study\雷达数据\mydata\test\D7\')
seg_data('E:\study\雷达数据\mydata\test\SN_132\')
seg_data('E:\study\雷达数据\mydata\test\SN_9563\')
seg_data('E:\study\雷达数据\mydata\test\SN_C71\')
seg_data('E:\study\雷达数据\mydata\test\T62\')
seg_data('E:\study\雷达数据\mydata\test\ZIL131\')
seg_data('E:\study\雷达数据\mydata\test\ZSU_23_4\')

% read_data_to_mat('E:\study\雷达数据\mydata\train\2S1\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\BRDM_2\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\BTR_60\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\D7\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\SN_132\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\SN_9563\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\SN_C71\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\T62\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\ZIL131\','train')
% read_data_to_mat('E:\study\雷达数据\mydata\train\ZSU_23_4\','train')
% 
% read_data_to_mat('E:\study\雷达数据\mydata\test\2S1\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\BRDM_2\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\BTR_60\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\D7\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\SN_132\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\SN_9563\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\SN_C71\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\T62\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\ZIL131\','test')
% read_data_to_mat('E:\study\雷达数据\mydata\test\ZSU_23_4\','test')
